[package]
name = "wallpaper_of_life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.42.0"
x11 = "2.19.1"
#x11_dl = "2.19.1"