[package]
name = "wallpaper_of_life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = {version = "0.9.0", features = ["glx", "randr", "render"] }